### PR TITLE
Prevent user from booking more than 60 days in advance

### LINKED ISSUE #85: limit bookings to 60 days in the future

### PR DESCRIPTION
**Pull request by welvin21**
Closes #85

### CODE REVIEW

**Comment by welvin21** [comment]
Closes #85

**Review by 98sean98 — APPROVED** [review]

**Comment by 98sean98** [comment]
tested the code right?

**Comment by welvin21** [comment]
> tested the code right?

Yepp, it works

**Comment by welvin21** [comment]
@utkarsh867 can this and #87 be merged??

**Review by utkarsh867 — APPROVED** [review]

**Pull request merged**
